### ISSUE TITLE
how long do you expect this repo to live?

### ISSUE THREAD

**Issue by bunnymatic** [krzyzanowskim/dm-paperclip-s3#2]
hey there

I was just recently updating an old project which still depends on this gem and it made me wonder (as i fought with other gem updates) if you have plans to leave this for *ever* or if you expect this repo to get retired at some point.

I can certainly fork it and own my own copy.  just looking forward.

maybe some day i'd migrate to something new but for now, i'd love to keep using this.

thanks for any info.
and thanks for keeping it around

cheers
mr rogers

**Comment by krzyzanowskim** [comment]
long live repo 🎉
I have no plans to ths repo. Now I'll remember to not delete it :-)

**Comment by bunnymatic** [comment]
Thanks much!
